---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Konfiguracja DNS master
#--------------------------------------

  - name: Potrzebne paczki
    dnf:
      name: "{{ dns_pkgs }}"
      state: present
    tags: 
      - "DNS_PKGS"
      - "DNS_SLAVE"

  - name: named.conf
    copy:
        src: named.conf
        dest: /etc/named.conf
        owner: root
        group: root
        mode: 0644
    tags: 
      - "DNS_CFG_FILES"
      - "DNS_SLAVE"

  - name: bind9
    systemd:
      name: named
      enabled: yes
      state: reloaded
    tags: 
      - "DNS_SRV"
      - "DNS_SLAVE"

  - name: firewall
    firewalld:
      service: dns
      state: enabled
      permanent: yes
    tags:
      - "DNS_FW"
      - "DNS_SLAVE"