---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Playbook główny.
#--------------------------------------
- hosts: all
  gather_facts: True
  any_errors_fatal: True
  remote_user: root

  roles:
    - role: os_cfg
    - role: dns_master 
      when: master_dns
    - role: dns_secondary
      when: second_dns
    - role: dhcpd_srv
      when: master_dhcp
    - role: ha
      when: ha_srv