---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Playbook główny.
#--------------------------------------
- hosts: all
  gather_facts: True
  any_errors_fatal: True
  remote_user: root

  roles:
    - role: os_cfg
      tags: 
         - "OS"
    - role: dns_master 
      when: master_dns
      tags:
        - "DNS"
    - role: dhcpd_srv
      when: master_dhcp
    - role: ha
      when: ha_srv
    - role: web_srv
      when: web_srvs
      tags:
        - "WEB"
    - role: ba_repo
      when: web_srvs and ba_repo
