---
#--------------------------------------
# Przygotowanie domowego RPi do roli kotrolera Home-Assistant w podmanie
#--------------------------------------

  - name: Potrzebne paczki
    dnf:
      name: "{{ ha_pkgs }}"
      state: present
    tags: 
      - "HA_PKGS"
      - "HA"

  - name: User do kontenera
    user:
      name: homeass
      comment: "Hołm Assistant"
    tags: 
      - "HA"
      - "HA_USR"

  - name: Wymiana klucza z homeass
    authorized_key:
     user: homeass
     state: present
     key: "{{ lookup('file', '/home/marcinek/.ssh/id_ecdsa-gauss.pub') }}"
    tags: 
      - "HA"
      - "HA_USR"

  - name: firewall
    firewalld:
      port: 8123/tcp
      permanent: yes
      state: enabled
    tags:
      - "HA"
      - "HA_FW"

  - name: Katalog konfiguracji
    file:
      path: /home/homeass/hass_cfg
      state: directory
      owner: homeass
      group: homeass
      mode: 0755
    tags:
      - "HA"
      - "HA_CFG"

  - name: Kontener Home Assistant
    become: yes
    become_user: homeass
    containers.podman.podman_container:
      name: homeass
      image: ghcr.io/home-assistant/home-assistant:stable
      init: no
      network: host
      restart_policy: "on-failure:3"
      state: started
      volume:
        - "/etc/localtime:/etc/localtime:ro"
        - "/home/homeass/hass_cfg:/config:Z"
      generate_systemd:
        path: /home/homeass
        container_prefix: ha
        restart_policy: "on-failure"
    tags:
      - "HA"
      - "HA_CONTAINER"

  - name: Chrum chrum na systemd
    lineinfile:
      path: /home/homeass/ha-homeass.service
      insertafter: 'Service'
      line: "User=homeass"
    tags:
      - "HA"
      - "HA_SYSD"

  - name: Kontenener pezez systemd
    copy: 
      src: /home/homeass/ha-homeass.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644
      remote_src: yes
    tags:
      - "HA"
      - "HA_SYSD"

  - name: Reload systemd
    systemd: 
      daemon_reload: yes
    tags:
      - "HA"
      - "HA_SYSD"

  - name: Enejbyl homeass kontener
    systemd:
      name: ha-homeass
      enabled: yes
      state: stopped
    tags:
      - "HA"
      - "HA_SYSD"