---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Konfiguracja DNS master
#--------------------------------------

  - name: Potrzebne paczki
    dnf:
      name: "{{ dnsmasq_pkgs }}"
      state: present
    tags: 
      - "DNS_PKGS"
      - "DNS_MASTER"

  - name: Konfiguracja lokalna do dnsmasq.conf.d
    copy:
        src: devnull.conf
        dest: /etc/dnsmasq.d/devnull.conf
        owner: root
        group: root
        mode: 0644
    tags: 
      - "DNS_CFG_FILES"
      - "DNS_MASTER"

  - name: Wrzutka upstreamów DNS
    copy:
        src: dnsmasq-forwarders.conf
        dest: /etc/dnsmasq-forwarders.conf
        owner: root
        group: root
        mode: 0644
    tags: 
      - "DNS_CFG_FILES"
      - "DNS_MASTER"

  - name: Włączenie parsowania dropinów na dnsmasq
    lineinfile:
      path: /etc/dnsmasq.conf
      regexp: '^conf-dir='
      line: conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig
    tags: 
      - "DNS_CFG_FILES"
      - "DNS_MASTER"

  - name: Włączenie słuchania na wszystkich międzymordziach
    lineinfile:
      path: /etc/dnsmasq.conf
      regexp: '^interface=lo'
      line: '# interface=lo'
    tags: 
      - "DNS_CFG_FILES"
      - "DNS_MASTER"

  - name: Ustawianie cache na coś więcej niż 150 wpisów. Np. na 1500
    lineinfile:
      path: /etc/dnsmasq.conf
      regexp: '#cache-size='
      line: 'cache-size=1500'
    tags: 
      - "DNS_CFG_FILES"
      - "DNS_MASTER"

  - name: Synchronizacja devnull-hosts z /etc/hosts
    block:
      # - name: czytanie /etc/hosts na zdalnych hostach
      #   ansible.builtin.slurp:
      #     src: /etc/hosts
      #   register: remote_hosts

      # - name: Konwersja zdalnych /etc/hosts na linijki
      #   ansible.builtin.set_fact:
      #     remote_lines: "{{ remote_hosts['content'] | b64decode | splitlines() }}"

      - name: Dodawanie linijek z devnull-hosts do zdalnych /etc/hosts
        vars:
          remote_lines: "{{ lookup('file', '/etc/hosts').splitlines() }}"
        ansible.builtin.lineinfile:
          path: /etc/hosts
          line: "{{ item }}"
          state: present
        loop: "{{ local_hosts_file }}"
        when: item not in remote_lines
      # - name: tvn24
      #   debug:
      #     var: local_hosts_file
    vars:
      local_hosts_file: "{{ lookup('file', 'devnull-hosts').splitlines() }}"
    tags: 
      - "DNS_ZONES"
      - "DNS_MASTER"
      - "SYNC_HOSTS"

  - name: "(Re)startowanie dnsmasq"
    systemd:
      name: dnsmasq
      enabled: yes
      state: restarted
    tags: 
      - "DNS_SRV"
      - "DNS_MASTER"
      - "DNS_ZONES"
      - "DNS_CFG_FILES"

  - name: firewall
    firewalld:
      service: dns
      state: enabled
      permanent: yes
      immediate: True
    tags:
      - "DNS_FW"
      - "DNS_MASTER"
      - "DNS_SRV"
