---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Wstępna konfiguracja OS.
#--------------------------------------

  - name: Kolarze do sudo
    copy:
        src: wheel.conf
        dest: /etc/sudoers.d/wheel
        owner: root
        group: root
        mode: 0440
    tags: "CFG_FILES"

  - name: Pokaż flaki
    debug:
        var: ansible_facts
    tags: "DBG"

#  - name: Lista połączeń nmcli
#    shell: nmcli -t  c s  --active | cut -f 1,4 -d ':' 
#    register: nmout
#    tags: "NET"
    
#  - name: pokaż połączenia eth0
#    debug: 
#        msg: "Jest {{ item }}!"
#    when: item is regex(".*{{ hostvars['ifname'] }}$")
#    with_items: "{{ nmout.stdout_lines }}"
#    tags: "NET"

  - name: Potrzebne paczki
    dnf:
      name: "{{ pkgs }}"
      state: present
    tags: "PKGS"

  - name: chrony.conf z szablonu
    template:
      src: chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644
      backup: yes
    tags: NTP

  - name: Restart chronyd
    service:
      name: chronyd
      state: restarted
    tags: NTP
