---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Konfiguracja serwera DHCPD master
#--------------------------------------

  - name: Potrzebne paczki
    dnf:
      name: "{{ dhcpd_pkgs }}"
      state: present
    tags: 
      - "DHCP_PKGS"
      - "DHCP_SRV"

  - name: zmienne
    debug:
      msg: "DHCP: {{ master_dhcp }}, DNS: {{ master_dhcp }}"
    tags:
      - "DHCP_SRV"


  - name: kea-dhcp4.conf
    copy:
        src: kea-dhcp4.conf
        dest: /etc/kea/kea-dhcp4.conf
        owner: root
        group: root
        mode: 0644
    tags: 
      - "DHCP_SRV"
      - "DHCP4"

  - name: kea-dhcp4
    systemd:
      name: kea-dhcp4
      enabled: no
      state: stopped
    tags: 
      - "DHCP4"
      - "DHCP_SRV"

  - name: firewall
    firewalld:
      service: dhcp
      state: enabled
      permanent: yes
    tags:
      - "DHCP_SRV"
      - "DHCP4"