---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Konfiguracja serwera DHCPD master
#--------------------------------------

  - name: Potrzebne paczki
    dnf:
      name: "{{ dhcpd_pkgs }}"
      state: present
    tags: 
      - "DHCP_PKGS"
      - "DHCP_SRV"

  - name: zmienne
    debug:
      msg: "DHCP: {{ master_dhcp }}, DNS: {{ master_dhcp }}"
    tags:
      - "DHCP_SRV"


  # - name: named.conf
  #   copy:
  #       src: named.conf
  #       dest: /etc/named.conf
  #       owner: root
  #       group: root
  #       mode: 0644
  #   tags: 
  #     - "DNS_CFG_FILES"
  #     - "DNS_MASTER"

  # - name: db.devnull
  #   copy:
  #       src: db.devnull
  #       dest: /var/named/db.devnull
  #       owner: root
  #       group: root
  #       mode: 0644
  #   tags: 
  #     - "DNS_ZONES"
  #     - "DNS_MASTER"

  # - name: db.192
  #   copy:
  #       src: db.192
  #       dest: /var/named/db.192
  #       owner: root
  #       group: root
  #       mode: 0644
  #   tags: 
  #     - "DNS_ZONES"
  #     - "DNS_MASTER"

  # - name: bind9
  #   systemd:
  #     name: named
  #     enabled: yes
  #     state: started
  #   tags: 
  #     - "DNS_SRV"
  #     - "DNS_MASTER"

  # - name: firewall
  #   firewalld:
  #     service: dns
  #     state: enabled
  #     permanent: yes
  #   tags:
  #     - "DNS_FW"
  #     - "DNS_MASTER"