---
#--------------------------------------
# Przygotowanie domowego RPi do roli serwera-pomagiera sieci LAN.
#   Konfiguracja serwera DHCPD master
#--------------------------------------

  - name: Potrzebne paczki
    dnf:
      name: "{{ dhcpd_pkgs }}"
      state: present
    tags: 
      - "DHCP_PKGS"
      - "DHCP_SRV"

  - name: zmienne
    debug:
      msg: "DHCP: {{ master_dhcp }}, DNS: {{ master_dhcp }}"
    tags:
      - "DHCP_SRV"


  - name: kea-dhcp4.conf
    copy:
        src: kea-dhcp4.conf
        dest: /etc/kea/kea-dhcp4.conf
        owner: root
        group: root
        mode: 0644
    tags: 
      - "DHCP_SRV"
      - "DHCP4"

  # - name: db.devnull
  #   copy:
  #       src: db.devnull
  #       dest: /var/named/db.devnull
  #       owner: root
  #       group: root
  #       mode: 0644
  #   tags: 
  #     - "DNS_ZONES"
  #     - "DNS_MASTER"

  # - name: db.192
  #   copy:
  #       src: db.192
  #       dest: /var/named/db.192
  #       owner: root
  #       group: root
  #       mode: 0644
  #   tags: 
  #     - "DNS_ZONES"
  #     - "DNS_MASTER"

  - name: kea-dhcp4
    systemd:
      name: kea-dhcp4
      enabled: yes
      state: reloaded
    tags: 
      - "DHCP4"
      - "DHCP_SRV"

  - name: firewall
    firewalld:
      service: dhcp
      state: enabled
      permanent: yes
    tags:
      - "DHCP_SRV"
      - "DHCP4"